# Generated by Django 5.1.6 on 2025-07-01 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r2', models.FloatField()),
                ('plot_closing', models.FilePathField(blank=True, null=True, path='static/plots')),
                ('plot_cmp', models.FilePathField(blank=True, null=True, path='static/plots')),
                ('metrics', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['ticker', 'created'], name='core_predic_ticker_d44c38_idx')],
            },
        ),
    ]
