# Generated by Django 5.1.6 on 2025-07-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_pro',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='plot_closing',
            field=models.CharField(default='default.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediction',
            name='plot_cmp',
            field=models.CharField(default='default.png', max_length=255),
            preserve_default=False,
        ),
    ]
